### ISSUE TITLE
Unable to build on MacOS

### ISSUE THREAD

**Issue by marcpabst** [EnzymeAD/rust#145]
Hi, enzyme looks super cool, and now that it’s on its way into nightly, I’d like to play around with it a bit. I’m following the instructions in the README, but the build always errors with the following output:

```
[92/93] Install the project...
-- Install configuration: "Release"
-- Installing: /Users/X/rust/build/build/aarch64-apple-darwin/enzyme/lib/cmake/Enzyme/EnzymeConfig.cmake
-- Installing: /Users/X/rust/build/build/aarch64-apple-darwin/enzyme/lib/cmake/Enzyme/EnzymeConfigVersion.cmake
-- Installing: /Users/X/rust/build/build/aarch64-apple-darwin/enzyme/lib/cmake/Enzyme/EnzymeTargets.cmake
-- Installing: /Users/X/rust/build/build/aarch64-apple-darwin/enzyme/lib/cmake/Enzyme/EnzymeTargets-release.cmake
-- Installing: /Users/X/rust/build/build/aarch64-apple-darwin/enzyme/lib/LLVMEnzyme-17.dylib
-- Installing: /Users/X/rust/build/build/aarch64-apple-darwin/enzyme/lib/ClangEnzyme-17.dylib
-- Installing: /Users/X/rust/build/build/aarch64-apple-darwin/enzyme/lib/LLDEnzyme-17.dylib
cargo:root=/Users/X/rust/build/build/aarch64-apple-darwin/enzyme
	finished in 61.092 seconds
thread 'main' panicked at src/lib.rs:1605:24:
src.symlink_metadata() failed with No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:18:44
```

Any idea how to address this? I'm on an a Macbook Pro M2

Edit: Looks like I'm not the only one with this problem: https://github.com/EnzymeAD/rust/issues/27#issuecomment-1758826871

**Comment by ZuseZ4** [comment]
Hi, yes indeed I have been ignoring MacOS support a bit since I had no good way of debugging it. I am happy to take an hour one of these days to sit down for some co-programming and adjust the paths and file endings to whatever Apple prefers, but other than that I have no good way of making progress here beside of waiting for PRs fixing this. Would you be interested to work on it?

**Comment by marcpabst** [comment]
Hey, I’m generally very happy to help with debugging path problems, as long as no understanding of compiler internals or LLVM stuff is needed!

**Comment by ZuseZ4** [comment]
Yep no worries that's not needed, the bugs are likely that I either hardcoded some paths or file endings that don't exist on linux. So if you are fine with screen-sharing, we can just compile it on your PC with some debug flags and fix all the bugs along the way. Do either Thursday or Friday after 8am PDT work for you?

**Comment by marcpabst** [comment]
Great, Thursday 8am PDT / 3pm UTC works! I can send you a Teams link if that's ok!

**Comment by ZuseZ4** [comment]
rust/src/bootstrap/src/core/build_steps/compile.rs
line 1652

**Comment by marcpabst** [comment]
Changing `LINK_FLAGS "-Wl,-flat_namespace -Wl,-undefined -Wl,suppress")` to  `LINK_FLAGS "-dynamiclib -Wl,-undefined,dynamic_lookup,-flat_namespace -Wl,-undefined -Wl,suppress")` in 
`src/tools/enzyme/enzyme/Enzyme/CMakeLists.txt:155`

```
if (APPLE)
# Darwin-specific linker flags for loadable modules.
set_target_properties(LLVMEnzyme-${LLVM_VERSION_MAJOR} PROPERTIES
    LINK_FLAGS "-dynamiclib -Wl,-undefined,dynamic_lookup,-flat_namespace -Wl,-undefined -Wl,suppress")
if (${Clang_FOUND})
set_target_properties(ClangEnzyme-${LLVM_VERSION_MAJOR} PROPERTIES
    LINK_FLAGS "-dynamiclib -Wl,-undefined,dynamic_lookup,-flat_namespace -Wl,-undefined -Wl,suppress")
endif()
set_target_properties(LLDEnzyme-${LLVM_VERSION_MAJOR} PROPERTIES
    LINK_FLAGS "-dynamiclib -Wl,-undefined,dynamic_lookup,-flat_namespace -Wl,-undefined -Wl,suppress")
endif()
```

results in

```
[1/57] Linking CXX shared module Enzyme/LLVMEnzyme-17.dylib
FAILED: Enzyme/LLVMEnzyme-17.dylib
: && /usr/bin/c++ -Wall -fno-rtti -ffunction-sections -fdata-sections -fPIC -arch arm64 -stdlib=libc++ -Werror=unused-variable -Werror=dangling-else -Werror=unused-but-set-variable -Werror=return-type -Werror=nonnull -Werror=unused-result -Werror=reorder -Werror=switch -O2 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -bundle -Wl,-headerpad_max_install_names -dynamiclib -Wl,-undefined,dynamic_lookup,-flat_namespace -Wl,-undefined -Wl,suppress -o Enzyme/LLVMEnzyme-17.dylib Enzyme/CMakeFiles/LLVMEnzyme-17.dir/ActivityAnalysis.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/ActivityAnalysisPrinter.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/CApi.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/CacheUtility.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/CallDerivatives.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/DiffeGradientUtils.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/DifferentialUseAnalysis.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/Enzyme.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/EnzymeLogic.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/FunctionUtils.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/GradientUtils.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/InstructionBatcher.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/JLInstSimplify.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/MustExitScalarEvolution.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/PreserveNVVM.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/TraceGenerator.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/TraceInterface.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/TraceUtils.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/Utils.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/SCEV/ScalarEvolutionExpander.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/TypeAnalysis/TypeTree.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/TypeAnalysis/TypeAnalysis.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/TypeAnalysis/TypeAnalysisPrinter.cpp.o Enzyme/CMakeFiles/LLVMEnzyme-17.dir/TypeAnalysis/RustDebugInfo.cpp.o  -Wl,-rpath,@loader_path/../lib -Wl,-rpath,/Users/marc/rust/build/aarch64-apple-darwin/llvm/lib  /Users/marc/rust/build/aarch64-apple-darwin/llvm/lib/libLLVM.dylib && :
clang: error: invalid argument '-bundle' not allowed with '-dynamiclib'
```

**Comment by ZuseZ4** [comment]
Looking through old PRs and online docs, you can apparently get rid of `-bundle` flags by changing the CMake build type from Module to something else, but that caused a lot of compilation failures in CI, so not sure if its' the right path to proceed: https://github.com/EnzymeAD/Enzyme/pull/1683

**Comment by marcpabst** [comment]
I managed to get it to build (I'll try to re-trace my steps later)! I then an
```
rustup toolchain link enzyme build/host/stage1
rustup toolchain install nightly
```
But now I'm stuck with
```
% rust-autodiff-test % cargo +enzyme run -r
   Compiling rust-autodiff-test v0.1.0 (/Users/marc/rust-autodiff-test)
error: the `-Z unstable-options` flag must also be passed to enable the flag `check-cfg`
```

**Comment by marcpabst** [comment]
`RUSTFLAGS="-Z unstable-options"` did the trick! Thanks for your help, looks like it's working fine now!

**Comment by marcpabst** [comment]
What fixed it in the end was mainly https://github.com/EnzymeAD/Enzyme/pull/1683 plus some file naming shenanigans, so that the compiler can find the right dylib.

**Comment by ZuseZ4** [comment]
Can you share your final rust changes so we can merge them?

**Comment by marcpabst** [comment]
[Sure!](https://github.com/EnzymeAD/rust/commit/46296c523f3b04354edd8b00c86d60de10f6ee83)

**Comment by ZuseZ4** [comment]
But only of rustc which I'd expect, but not of your binary, right? I.e. if you run `cargo +enzyme build` and look at the resulting binary, it won't depend on the two, right?

**Comment by marcpabst** [comment]
No, looks its weirdly an actual dependency of the binary: 

```
(base) marc@eduroam-int-dhcp-97-103-145 rust-autodiff-test % ./target/release/rust-autodiff-test
dyld[58776]: <FED69655-D158-3B3E-B082-72B7E293A37E> /Users/marc/rust-autodiff-test/target/release/rust-autodiff-test
dyld[58776]: Library not loaded: @rpath/libLLVMEnzyme-17.dylib
  Referenced from: <FED69655-D158-3B3E-B082-72B7E293A37E> /Users/marc/rust-autodiff-test/target/release/rust-autodiff-test
  Reason: no LC_RPATH's found
zsh: abort      ./target/release/rust-autodiff-test
```

**Comment by ZuseZ4** [comment]
That's bad, but by default (if Enzyme isn't moved between compiling and running the binary) is going to work, right?
So I'd still merge the fix and then try to remove the dependency next.

cc @tgymnich since we just talked about it.

**Comment by marcpabst** [comment]
Yes, `cargo run` works, but calling the binary directly results in the error below (I assume cargo sets some environment variables?)  

I only noticed this because I tried to build a Python module and Python's importlib gives a helpful error when it can't locate a dynaimc library.

**Comment by ZuseZ4** [comment]
I just merged a different fix from Tim, @marcpabst  can you try to rebuild and see if A) it works and B) if you still have the runtime dependency of your resulting test/example binaries on LLVM and Enzyme?

**Comment by marcpabst** [comment]
This is what I'm seeing:

```
[10/11] Install the project...
-- Install configuration: "Release"
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: no LC_RPATH load command with path: /Users/marc/tmo/rust/build/aarch64-apple-darwin/llvm/lib found in: /Users/marc/tmo/rust/build/aarch64-apple-darwin/enzyme/lib/libEnzyme-17.dylib (for architecture arm64), required for specified option "-delete_rpath /Users/marc/tmo/rust/build/aarch64-apple-darwin/llvm/lib"
-- Installing: /Users/marc/tmo/rust/build/aarch64-apple-darwin/enzyme/lib/libEnzymeBCLoad-17.dylib
cargo:root=/Users/marc/tmo/rust/build/aarch64-apple-darwin/enzyme
	finished in 5.101 seconds
thread 'main' panicked at src/lib.rs:1605:24:
src.symlink_metadata() failed with No such file or directory (os error 2)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0e09125c6c3c2fd70d7de961bcf0e51575235fad/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/0e09125c6c3c2fd70d7de961bcf0e51575235fad/library/core/src/panicking.rs:72:14
   2: bootstrap::Build::copy_internal
             at ./src/bootstrap/src/lib.rs:1605:24
   3: bootstrap::Build::copy
             at ./src/bootstrap/src/lib.rs:1593:9
   4: <bootstrap::core::build_steps::compile::Assemble as bootstrap::core::builder::Step>::run
             at ./src/bootstrap/src/core/build_steps/compile.rs:1657:13
   5: bootstrap::core::builder::Builder::ensure
             at ./src/bootstrap/src/core/builder.rs:2192:23
   6: bootstrap::core::builder::Builder::compiler
             at ./src/bootstrap/src/core/builder.rs:989:9
   7: <bootstrap::core::build_steps::compile::Std as bootstrap::core::builder::Step>::make_run
             at ./src/bootstrap/src/core/build_steps/compile.rs:107:23
   8: bootstrap::core::builder::StepDescription::maybe_run
             at ./src/bootstrap/src/core/builder.rs:328:13
   9: bootstrap::core::builder::StepDescription::run
             at ./src/bootstrap/src/core/builder.rs:398:17
  10: bootstrap::core::builder::Builder::run_step_descriptions
             at ./src/bootstrap/src/core/builder.rs:981:9
  11: bootstrap::core::builder::Builder::execute_cli
             at ./src/bootstrap/src/core/builder.rs:962:9
  12: bootstrap::Build::build
             at ./src/bootstrap/src/lib.rs:672:13
  13: bootstrap::main
             at ./src/bootstrap/src/bin/main.rs:85:5
  14: core::ops::function::FnOnce::call_once
             at /rustc/0e09125c6c3c2fd70d7de961bcf0e51575235fad/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Build completed unsuccessfully in 0:00:14
```

**Comment by ZuseZ4** [comment]
Can you share what file it's looking for, and how your Enzyme build folder looks like?

**Comment by marcpabst** [comment]
It's looking for `src = "/Users/marc/tmo/rust/build/aarch64-apple-darwin/enzyme/build/Enzyme/libEnzyme-17.so"`.

```
(base) marc@Marcs-MBP-2 rust % ls /Users/marc/tmo/rust/build/aarch64-apple-darwin/enzyme/build/Enzyme/
BinopDerivatives.inc		BlasDerivatives.inc		BlasTA.inc			CallDerivatives.inc.d		InstructionDerivatives.inc.d	LLVMEnzyme-17.dylib
BinopDerivatives.inc.d		BlasDerivatives.inc.d		BlasTA.inc.d			Clang				IntrinsicDerivatives.inc	cmake_install.cmake
BlasAttributor.inc		BlasDiffUse.inc			CMakeFiles			ClangEnzyme-17.dylib		IntrinsicDerivatives.inc.d	libEnzyme-17.dylib
BlasAttributor.inc.d		BlasDiffUse.inc.d		CallDerivatives.inc		InstructionDerivatives.inc	LLDEnzyme-17.dylib
```

**Comment by ZuseZ4** [comment]
Ah good, only the file ending is wrong (so vs dylib), but at least the libenzyme version exists. Do you want to quickly test a fix and make a PR if you find that we're under macos? 
cc @tgymnich, did your Enzyme build with .so endings, or why did it work for you locally?

**Comment by tgymnich** [comment]
@ZuseZ4 maybe I overlooked some error. It should use .dylib on mac. Possibly also .dll on windows?

**Comment by marcpabst** [comment]
Some quick changes in `src/bootstrap/src/core/build_steps/compile.rs` lead to a successful build:

```rust 
  if let Some(enzyme_install) = enzyme_install {
      let src_lib = enzyme_install.join("build/Enzyme/libEnzyme-17.so");

      let libdir = builder.sysroot_libdir(build_compiler, build_compiler.host);
      let target_libdir = builder.sysroot_libdir(target_compiler, target_compiler.host);
      let dst_lib = libdir.join("libEnzyme-17.so");
      let target_dst_lib = target_libdir.join("libEnzyme-17.so");
      builder.copy(&src_lib, &dst_lib);
      builder.copy(&src_lib, &target_dst_lib);
  }
```

```rust
if let Some(enzyme_install) = enzyme_install {
    let src_lib = enzyme_install.join("build/Enzyme/libEnzyme-17.dylib");

    let libdir = builder.sysroot_libdir(build_compiler, build_compiler.host);
    let target_libdir = builder.sysroot_libdir(target_compiler, target_compiler.host);
    let dst_lib = libdir.join("libEnzyme-17.dylib");
    let target_dst_lib = target_libdir.join("libEnzyme-17.dylib");
    builder.copy(&src_lib, &dst_lib);
    builder.copy(&src_lib, &target_dst_lib);
}
```

**Comment by ZuseZ4** [comment]
Windows is unfortunately unsupported anyway by Enzyme core, since MSVC dislikes Enzyme's interesting
`#declare private public`

ok, then I can make a quick PR.

**Comment by marcpabst** [comment]
Unfortunately, looks like the runtime dependency issue persists - here's the `otool -l` output:

```
./target/release/rust-autodiff-test:
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000100000000
  fileoff 0
 filesize 0
  maxprot 0x00000000
 initprot 0x00000000
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 552
  segname __TEXT
   vmaddr 0x0000000100000000
   vmsize 0x0000000000048000
  fileoff 0
 filesize 294912
  maxprot 0x00000005
 initprot 0x00000005
   nsects 6
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x00000001000044e0
      size 0x0000000000037e88
    offset 17632
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x000000010003c368
      size 0x0000000000000318
    offset 246632
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 12 (size of stubs)
Section
  sectname __const
   segname __TEXT
      addr 0x000000010003c680
      size 0x000000000000427c
    offset 247424
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __gcc_except_tab
   segname __TEXT
      addr 0x00000001000408fc
      size 0x0000000000001260
    offset 264444
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x0000000100041b5c
      size 0x0000000000000ef8
    offset 269148
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __eh_frame
   segname __TEXT
      addr 0x0000000100042a58
      size 0x00000000000055a8
    offset 272984
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x6800000b
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 232
  segname __DATA_CONST
   vmaddr 0x0000000100048000
   vmsize 0x0000000000004000
  fileoff 294912
 filesize 16384
  maxprot 0x00000003
 initprot 0x00000003
   nsects 2
    flags 0x10
Section
  sectname __got
   segname __DATA_CONST
      addr 0x0000000100048000
      size 0x0000000000000218
    offset 294912
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 66 (index into indirect symbol table)
 reserved2 0
Section
  sectname __const
   segname __DATA_CONST
      addr 0x0000000100048218
      size 0x0000000000002038
    offset 295448
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 3
      cmd LC_SEGMENT_64
  cmdsize 472
  segname __DATA
   vmaddr 0x000000010004c000
   vmsize 0x0000000000004000
  fileoff 311296
 filesize 16384
  maxprot 0x00000003
 initprot 0x00000003
   nsects 5
    flags 0x0
Section
  sectname __data
   segname __DATA
      addr 0x000000010004c000
      size 0x0000000000000038
    offset 311296
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __thread_vars
   segname __DATA
      addr 0x000000010004c038
      size 0x00000000000000a8
    offset 311352
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000013
 reserved1 0
 reserved2 0
Section
  sectname __thread_data
   segname __DATA
      addr 0x000000010004c0e0
      size 0x0000000000000020
    offset 311520
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000011
 reserved1 0
 reserved2 0
Section
  sectname __thread_bss
   segname __DATA
      addr 0x000000010004c100
      size 0x0000000000000032
    offset 311552
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000012
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x000000010004c138
      size 0x00000000000000c0
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 4
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x0000000100050000
   vmsize 0x0000000000014000
  fileoff 327680
 filesize 71136
  maxprot 0x00000001
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 5
      cmd LC_DYLD_CHAINED_FIXUPS
  cmdsize 16
  dataoff 327680
 datasize 1456
Load command 6
      cmd LC_DYLD_EXPORTS_TRIE
  cmdsize 16
  dataoff 329136
 datasize 80
Load command 7
     cmd LC_SYMTAB
 cmdsize 24
  symoff 329912
   nsyms 766
  stroff 342704
 strsize 52856
Load command 8
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 696
     iextdefsym 696
     nextdefsym 3
      iundefsym 699
      nundefsym 67
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 342168
  nindirectsyms 133
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 9
          cmd LC_LOAD_DYLINKER
      cmdsize 32
         name /usr/lib/dyld (offset 12)
Load command 10
     cmd LC_UUID
 cmdsize 24
    uuid B9820BE7-FF08-373D-B415-2713C18CD8DB
Load command 11
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 14.0
      sdk 14.2
   ntools 1
     tool 3
  version 1022.1
Load command 12
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 13
       cmd LC_MAIN
   cmdsize 24
  entryoff 18196
 stacksize 0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1336.61.1
compatibility version 1.0.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libEnzyme-17.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 16
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 329216
 datasize 696
Load command 17
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 329912
 datasize 0
Load command 18
      cmd LC_CODE_SIGNATURE
  cmdsize 16
  dataoff 395568
 datasize 3248

```

**Comment by wsmoses** [comment]
> Windows is unfortunately unsupported anyway by Enzyme core, since MSVC dislikes Enzyme's interesting `#declare private public`
> 
> ok, then I can make a quick PR.

Enzyme is supported on Windows -- you just have to use clang to build not msvc

**Comment by ZuseZ4** [comment]
Agree there are workarounds including also e.g. WSL2, but as long as the default Rust `x86_64-pc-windows-msvc` toolchain doesn't work due to this Enzyme core issue, I won't go around and claim win support, because for the default setup of the majority that just wouldn't be true.

**Comment by marcpabst** [comment]
If this is an MSVC-related issue, does the ` x86_64-pc-windows-gnu` toolschain does then work fine on windows?

**Comment by ZuseZ4** [comment]
windows-gnu should work (iirc. someone confirmed it in another issue here), but please feel free to test and confirm that if you have a machine at hand.

**Comment by ZuseZ4** [comment]
@marcpabst Can you test if the dependency still exists on the latest master?

**Comment by marcpabst** [comment]
Hey, I've been having a bit of trouble cloning the repo - will give it another try tonight!

**Comment by ZuseZ4** [comment]
Maybe try to use https, like I do it in this PR? 
https://github.com/rust-lang/rust/pull/129176/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584
Let me know if this works.

**Comment by wsmoses** [comment]
@ZuseZ4 The error is here https://github.com/EnzymeAD/rust/blob/ab5490415bb28ef6cdd8045d116a9951aa171c8e/.gitmodules#L52 this should be changed to https like the others in the .gitmodules

**Comment by ZuseZ4** [comment]
That's the link I posted ^^ 
But out of curiosity, why? Is that for people who haven't configured a working keychain for authentication? 
I had it as `git@github.com...` for months if not years and it used to work for others.
The reason why I changed it during upstreaming is that Rust CI also didn't work with the git link:
https://github.com/rust-lang/rust/pull/129176

**Comment by marcpabst** [comment]
Thanks, I'll give it another go later!

**Comment by jedbrown** [comment]
I think this issue is settled, but just noting that `git clone --recursive` should work out of the box even for people who don't have GitHub accounts.

**Comment by ZuseZ4** [comment]
@marcpabst now that this code is partly in upstream rustc, can you please do me a favour and open an issue there (potentially linking here)?
https://github.com/rust-lang/rust/issues

**Comment by ZuseZ4** [comment]
@marcpabst This branch builds locally on an M4 https://github.com/rust-lang/rust/pull/136428 and I'll merge it over the next days into rustc, so I'm closing here. 
If you're still interested, do you want to retry (and open a new issue if the runtime dependency persists)?
