### ISSUE TITLE
Rust compiler Crash

### ISSUE THREAD

**Issue by e99243506bigplay** [EnzymeAD/rust#19]
I tried this code:

```rust
#![feature(bench_black_box)]
use autodiff::autodiff;
#[autodiff(dgrad, Reverse, Active, Active)]
fn get_output(amt: f64) -> (f64, f64) {
    (amt, 1.0)
}
fn main() {
    dgrad(1.0, (1.0, 1.0));
}

```

I expected to see this happen: Compile passed.

Instead, this happened: *explanation*

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (b25946088 2023-04-04)
binary: rustc
commit-hash: b25946088ccf2899d20e880657f79b51f2f34a02
commit-date: 2023-04-04
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.0
```

<details>Backtrace<summary>
</summary>
<p>

```
$ cargo clean && cargo +enzyme run --release -Z unstable-options --config 'lto="fat"'
   Compiling version_check v0.9.4
   Compiling proc-macro2 v1.0.56
   Compiling unicode-ident v1.0.8
   Compiling quote v1.0.26
   Compiling syn v1.0.109
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling autodiff v0.1.0 (**mask**/Enzyme-rust/library/autodiff)
   Compiling tstgrad v0.1.0 (/tmp/tstgrad)
[compiler/rustc_codegen_llvm/src/back/write.rs:672] &type_analysis = 0x00007f121983d450
thread '<unnamed>' panicked at 'Args len shouldn't differ. Please report this.', compiler/rustc_codegen_llvm/src/back/write.rs:610:9
stack backtrace:
   0:     0x7f1235309d1d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbc2fefb0f908071d
   1:     0x7f12353644cc - core::fmt::write::hcfd8dbbc6cc2d112
   2:     0x7f12352fb4f1 - std::io::Write::write_fmt::h1f8236ac48b73a6e
   3:     0x7f123530ca35 - std::panicking::default_hook::{{closure}}::h0a320c281e2cf753
   4:     0x7f123530c6a9 - std::panicking::default_hook::h77b8cf0f703442c9
   5:     0x7f12359ee979 - rustc_driver[9b7ca9a5e0bfcdc7]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:     0x7f123530d206 - std::panicking::rust_panic_with_hook::he2eed2d393b1bf6f
   7:     0x7f123530cfc9 - std::panicking::begin_panic_handler::{{closure}}::h9092161ea341e9d6
   8:     0x7f123530a1d4 - std::sys_common::backtrace::__rust_end_short_backtrace::h6596e6e3a8c8524c
   9:     0x7f123530cd39 - rust_begin_unwind
  10:     0x7f12352d1473 - core::panicking::panic_fmt::he089468669ab0c2e
  11:     0x7f1235c379fe - <rustc_codegen_llvm[b7afac244365f53b]::LlvmCodegenBackend as rustc_codegen_ssa[fde655230d926ecd]::traits::write::WriteBackendMethods>::autodiff
  12:     0x7f1235b6f8c0 - rustc_codegen_ssa[fde655230d926ecd]::back::write::start_executing_work::<rustc_codegen_llvm[b7afac244365f53b]::LlvmCodegenBackend>::{closure#4}
  13:     0x7f1235b44236 - std[330feb74f2e265b7]::sys_common::backtrace::__rust_begin_short_backtrace::<<rustc_codegen_llvm[b7afac244365f53b]::LlvmCodegenBackend as rustc_codegen_ssa[fde655230d926ecd]::traits::backend::ExtraBackendMethods>::spawn_thread<rustc_codegen_ssa[fde655230d926ecd]::back::write::start_executing_work<rustc_codegen_llvm[b7afac244365f53b]::LlvmCodegenBackend>::{closure#4}, core[889d80731517ff03]::result::Result<rustc_codegen_ssa[fde655230d926ecd]::back::write::CompiledModules, ()>>::{closure#0}, core[889d80731517ff03]::result::Result<rustc_codegen_ssa[fde655230d926ecd]::back::write::CompiledModules, ()>>
  14:     0x7f1235b794e4 - <<std[330feb74f2e265b7]::thread::Builder>::spawn_unchecked_<<rustc_codegen_llvm[b7afac244365f53b]::LlvmCodegenBackend as rustc_codegen_ssa[fde655230d926ecd]::traits::backend::ExtraBackendMethods>::spawn_thread<rustc_codegen_ssa[fde655230d926ecd]::back::write::start_executing_work<rustc_codegen_llvm[b7afac244365f53b]::LlvmCodegenBackend>::{closure#4}, core[889d80731517ff03]::result::Result<rustc_codegen_ssa[fde655230d926ecd]::back::write::CompiledModules, ()>>::{closure#0}, core[889d80731517ff03]::result::Result<rustc_codegen_ssa[fde655230d926ecd]::back::write::CompiledModules, ()>>::{closure#1} as core[889d80731517ff03]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  15:     0x7f12353173e3 - std::sys::unix::thread::Thread::new::thread_start::hb9f16899a8e702ff
  16:     0x7f12350c2bb5 - <unknown>
  17:     0x7f1235144d90 - <unknown>
  18:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (b25946088 2023-04-04) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C opt-level=3 -C panic=abort -C lto -C codegen-units=1 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread 'rustc' panicked at '**mask**/Enzyme-rust/compiler/rustc_codegen_ssa/src/back/write.rs:1860:17: panic during codegen/LLVM phase', compiler/rustc_middle/src/util/bug.rs:36:26
stack backtrace:
   0:     0x7f1235309d1d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbc2fefb0f908071d
   1:     0x7f12353644cc - core::fmt::write::hcfd8dbbc6cc2d112
   2:     0x7f12352fb4f1 - std::io::Write::write_fmt::h1f8236ac48b73a6e
   3:     0x7f123530ca35 - std::panicking::default_hook::{{closure}}::h0a320c281e2cf753
   4:     0x7f123530c6a9 - std::panicking::default_hook::h77b8cf0f703442c9
   5:     0x7f12359ee979 - rustc_driver[9b7ca9a5e0bfcdc7]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:     0x7f123530d206 - std::panicking::rust_panic_with_hook::he2eed2d393b1bf6f
   7:     0x7f12375f19f1 - std[330feb74f2e265b7]::panicking::begin_panic::<alloc[bf8cb5fae4f7b365]::string::String>::{closure#0}
   8:     0x7f12375dfffc - std[330feb74f2e265b7]::sys_common::backtrace::__rust_end_short_backtrace::<std[330feb74f2e265b7]::panicking::begin_panic<alloc[bf8cb5fae4f7b365]::string::String>::{closure#0}, !>
   9:     0x7f1235965184 - std[330feb74f2e265b7]::panicking::begin_panic::<alloc[bf8cb5fae4f7b365]::string::String>
  10:     0x7f12375bf61c - std[330feb74f2e265b7]::panic::panic_any::<alloc[bf8cb5fae4f7b365]::string::String>
  11:     0x7f12376e4e58 - rustc_middle[ecde786d3aeaed7c]::ty::context::tls::with_opt::<rustc_middle[ecde786d3aeaed7c]::util::bug::opt_span_bug_fmt<rustc_span[89f4c99c0bafe0ba]::span_encoding::Span>::{closure#0}, ()>
  12:     0x7f12377128e9 - rustc_middle[ecde786d3aeaed7c]::util::bug::opt_span_bug_fmt::<rustc_span[89f4c99c0bafe0ba]::span_encoding::Span>
  13:     0x7f123596ac55 - rustc_middle[ecde786d3aeaed7c]::util::bug::bug_fmt
  14:     0x7f1235c3a366 - <rustc_codegen_llvm[b7afac244365f53b]::LlvmCodegenBackend as rustc_codegen_ssa[fde655230d926ecd]::traits::backend::CodegenBackend>::join_codegen
  15:     0x7f1235b02ae7 - <rustc_interface[ca3972cb95dc44fe]::queries::Linker>::link
  16:     0x7f12359ce16f - rustc_interface[ca3972cb95dc44fe]::interface::run_compiler::<core[889d80731517ff03]::result::Result<(), rustc_errors[a8e81527e98fa9a3]::ErrorGuaranteed>, rustc_driver[9b7ca9a5e0bfcdc7]::run_compiler::{closure#1}>::{closure#0}
  17:     0x7f12359c4fe2 - std[330feb74f2e265b7]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ca3972cb95dc44fe]::util::run_in_thread_pool_with_globals<rustc_interface[ca3972cb95dc44fe]::interface::run_compiler<core[889d80731517ff03]::result::Result<(), rustc_errors[a8e81527e98fa9a3]::ErrorGuaranteed>, rustc_driver[9b7ca9a5e0bfcdc7]::run_compiler::{closure#1}>::{closure#0}, core[889d80731517ff03]::result::Result<(), rustc_errors[a8e81527e98fa9a3]::ErrorGuaranteed>>::{closure#0}, core[889d80731517ff03]::result::Result<(), rustc_errors[a8e81527e98fa9a3]::ErrorGuaranteed>>
  18:     0x7f12359cf7c9 - <<std[330feb74f2e265b7]::thread::Builder>::spawn_unchecked_<rustc_interface[ca3972cb95dc44fe]::util::run_in_thread_pool_with_globals<rustc_interface[ca3972cb95dc44fe]::interface::run_compiler<core[889d80731517ff03]::result::Result<(), rustc_errors[a8e81527e98fa9a3]::ErrorGuaranteed>, rustc_driver[9b7ca9a5e0bfcdc7]::run_compiler::{closure#1}>::{closure#0}, core[889d80731517ff03]::result::Result<(), rustc_errors[a8e81527e98fa9a3]::ErrorGuaranteed>>::{closure#0}, core[889d80731517ff03]::result::Result<(), rustc_errors[a8e81527e98fa9a3]::ErrorGuaranteed>>::{closure#1} as core[889d80731517ff03]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  19:     0x7f12353173e3 - std::sys::unix::thread::Thread::new::thread_start::hb9f16899a8e702ff
  20:     0x7f12350c2bb5 - <unknown>
  21:     0x7f1235144d90 - <unknown>
  22:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (b25946088 2023-04-04) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C opt-level=3 -C panic=abort -C lto -C codegen-units=1 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `tstgrad` (bin "tstgrad")
```

</p>
</details>

**Comment by ZuseZ4** [comment]
@bytesnake We should catch this in the macro, but I guess we can postpone that till we update to the latest rustc

**Comment by ZuseZ4** [comment]
@e99243506bigplay I am closing this, since it is against the Enzyme calling convention to return anything  except a single float scalar. You could e.g. pass one of the two as an extra &mut input arg and update it.
We do try to catch those as part of our macro but obviously failed here. 
Usually you should see a helpful error message that gives you this explanation, sorry for that!
